export const FRIENDSHIP_QUOTES = [
  "A good friend knows all your stories. A best friend helped you write them.",
  "Friends don't let friends sign bad transactions alone.",
  "Real friends don't ask where you've been. They ask what wallet you used.",
  "A friend is someone who sees the gas fee and pays it anyway.",
  "We didn't meet. We were deployed to the same block.",
  "True friendship: when you ape in together and neither of you checks the chart.",
  "Best friends are the people who make your problems their problems. Especially on-chain.",
  "A friend is just a stranger whose wallet you haven't rusted yet.",
  "We go together like a wallet and a private key.",
  "Friendship is knowing someone's seed phrase and never using it.",
  "Not all treasure is silver and gold. Some of it is a good Discord friend.",
  "You had me at 'gm'.",
  "Side by side or miles apart, real friends are never far from the heart — or the mempool.",
  "A loyal friend laughs at your jokes when they're not so good and sympathizes with your problems when they're not so bad. Also they don't frontrun you.",
  "Friendship is born the moment one person says to another: 'You too? I thought I was the only one who didn't understand the whitepaper.'",
  "The only thing better than a friend is a friend with on-chain receipts.",
  "Good friends are like stars. You don't always see them, but you know they're always in the same server.",
  "A true friend is someone who thinks you're a good egg even though you're slightly cracked.",
  "Friends are the family you choose. On Ritual, the chain chooses for you.",
  "Friendship is one mind in two bodies. And one RPC endpoint.",
  "If you have one good friend on the internet, you're richer than most.",
  "A friend is someone who gives you total freedom to be yourself — including posting your losses.",
  "Real friendship is when your friend comes online at 3am and you don't even ask why.",
  "We'll be friends forever because you already know too much.",
  "A friend is someone who can see the truth and pain in you even when you're busy fooling everyone else.",
  "Friendship is the only cement that will ever hold the crypto community together.",
  "You don't have to be crazy to be my friend. But it helps.",
  "A true friend is someone who is there for you when they'd rather be anywhere else. Like a bot that never goes offline.",
  "Friends are like blockchain nodes. The more you have, the more resilient you become.",
  "Strangers are just friends who haven't aped into the same token yet.",
  "A good friend is a connection to life — a tie to the past, a road to the future.",
  "Friendship is not about who you've known the longest. It's about who posted 'gm' first.",
  "Life is partly what we make it, and partly what it is made by the friends we choose — and partially by on-chain randomness.",
  "One measure of friendship consists not in the number of things friends can discuss, but in the number of things they need not mention.",
  "True friends are never apart. Maybe in distance, but never in the group chat.",
  "The language of friendship is not words but meaning. Also emojis.",
  "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still believes in your next trade.",
  "Some people go to priests. Others to poetry. I go to my friends.",
  "The most beautiful discovery true friends make is that they can grow separately without growing apart.",
  "A real friend is one who walks in when the rest of the world walks out — and mutes the server anyway.",
  "True friendship multiplies the good in life and divides its evils.",
  "A friend is someone who knows the song in your heart and can sing it back to you when you have forgotten the words.",
  "Friendship is the wine of life. Age it long enough and it only gets weirder.",
  "A friend is someone who makes it easy to believe in yourself.",
  "Friends are medicine for a wounded heart, and vitamins for a hopeful soul.",
  "There is nothing I would not do for those who are really my friends.",
  "A single rose can be my garden; a single friend, my world.",
  "I would rather walk with a friend in the dark than alone in the light.",
  "Find a group of people who challenge and inspire you; spend a lot of time with them. Ideally on Ritual.",
  "The greatest gift of life is friendship, and I have received it — via a smart contract.",
  "A friend is what the heart needs all the time.",
  "True friendship is never serene. Especially not when gas fees spike.",
  "Friendship is always a sweet responsibility, never an opportunity.",
  "A true friend never gets in your way unless you happen to be going down.",
  "Friends are those rare people who ask how we are and then wait to hear the answer.",
  "It is not so much our friends' help that helps us as the confident knowledge that they will help us.",
  "A friend is someone who gives you total freedom to be yourself — and your worst takes.",
  "Friendship is the only thing in the world concerning the usefulness of which all mankind are agreed. Also stablecoins.",
  "Don't walk in front of me — I may not follow. Don't walk behind me — I may not lead. Just walk beside me and check the floor price together.",
  "An honest enemy is better than a false friend. But an honest friend on Ritual Chain is better than both.",
  "A friend is one who overlooks your broken fence and admires the flowers in your garden. And your NFTs.",
  "There's not a word yet for old friends who've just met. But the chain knows.",
  "Friendship is born at the moment when one person says to another: 'What! You too? I thought I was the only one holding this bag.'",
  "The friend who holds your hand and says the wrong thing is made of dearer stuff than the one who stays away.",
  "In the sweetness of friendship let there be laughter and sharing of pleasures. And the occasional airdrop.",
  "Friendship is the golden thread that ties the heart of all the world. The chain just makes it immutable.",
  "There is nothing on this earth more to be prized than true friendship. Except maybe a confirmed block.",
  "A real friend is one who walks in when the rest of the world walks out.",
  "A friend may be waiting behind a stranger's face. Or behind a veiled card on Ritual.",
  "True friendship is sitting together in silence and feeling like it was the best conversation you ever had.",
  "Friendship is the comfort of knowing that even when you feel alone, you aren't.",
  "Good friends help you to find important things when you have lost them: your smile, your hope, your private key.",
  "Friends are those who, in moments of doubt, tell you it's going to be alright — and actually check the chart.",
  "A true friend is the greatest of all blessings and the one we take the least care to acquire.",
  "Friendship consists in forgetting what one gives and remembering what one receives. And never mentioning the rug.",
  "One loyal friend is worth ten thousand relatives. Especially when they send you the alpha.",
  "Friends are the siblings God never gave us, but the chain did.",
  "In prosperity our friends know us; in adversity we know our friends. Also in bear markets.",
  "A friend is the one who comes in when the whole world has gone out. And still calls the bottom wrong.",
  "Nothing makes the earth seem so spacious as to have friends at a distance. Or in a Discord server.",
  "Friendship is love without its wings. Also without the gas fees.",
  "A good friend is like a four-leaf clover: hard to find and lucky to have. A Ritual friend is rarer still.",
  "Truly great friends are hard to find, difficult to leave, and impossible to forget — or to de-list.",
  "Friends are the bacon bits in the salad bowl of life.",
  "A friend is someone who knows the melody of your heart and plays it back when you forget. Also sends you memes at 2am.",
  "I value the friend who for me finds time on his calendar, but I cherish the friend who for me does not consult his calendar.",
  "Friendship is the thread that ties us not just to each other, but to the best versions of ourselves.",
  "A true friend is someone who is always there for you, even when they'd rather be somewhere else — like a 24/7 validator node.",
  "We are all travelers in the wilderness of this world, and the best we can find in our travels is an honest friend. Or a good RPC.",
  "Friendship doubles your joys and divides your grief. On-chain, it's immutable.",
  "Friends are the people who make you smile brighter, laugh louder, and live better. Also the people who screenshot your losses.",
  "The antidote for fifty enemies is one friend. Unless those enemies are smart contract bugs.",
  "Friendship needs no words — it is solitude delivered from the anguish of loneliness. Like a silent node validating in the dark.",
  "A friend is someone who understands your past, believes in your future, and accepts you just the way you are — bags and all.",
  "Blessed are those who have the gift of making friends, for it is one of God's best gifts. The chain just assigns them randomly.",
  "Some friendships are timeless. Others are timestamped.",
  "Wishing to be friends is quick work, but friendship is a slow ripening fruit. Unless the chain accelerates it.",
  "A mirror reflects a man's face, but what he is really like is shown by the kind of friends he keeps — and the kind the chain picks for him.",
  "The best time to make friends is before you need them. The chain does not care about timing.",
  "The friend is the man who knows all about you, and still likes you. Even your on-chain history.",
  "Friendship is essentially a partnership. A decentralized one.",
  "A friend is one soul in two bodies. On Ritual, two wallets.",
  "What is a friend? A single soul dwelling in two bodies — and two separate hardware wallets.",
  "Laughter is not at all a bad beginning for a friendship, and it is far the best ending for one.",
  "Without friends, no one would choose to live, though he had all other goods. Aristotle probably had great Discord friends.",
  "Friendship improves happiness and abates misery by doubling our joy and dividing our grief. The math always works out.",
  "One of the most beautiful qualities of true friendship is to understand and to be understood.",
  "Friendship is always a sweet responsibility, never an opportunity — unless it comes with an airdrop.",
  "Friends show their love in times of trouble, not in happiness. And in bear markets. Especially bear markets.",
  "A real friend is one who walks in when the rest of the world walks out — and doesn't even check the floor price first.",
  "Friendship is a wildly underrated medication. Especially when taken on-chain.",
  "A friend is someone with whom you dare to be yourself. Even your degenerate self.",
  "The most I can do for my friend is simply be his friend. The chain can do a little more.",
  "Friendship is the only cement that will ever hold the world together. And maybe Solidity.",
  "A friend is a present you give yourself. The chain agrees.",
  "Life without a friend is death without a witness. Life without a Ritual friend is just a lonely validator.",
  "Friendship makes prosperity more shining and lessens adversity by dividing and sharing it. Also splits gas fees.",
  "Friendship is the shadow of the evening, which increases with the setting of the sun of life.",
  "The bird, a nest; the spider, a web; man, friendship. The blockchain, consensus.",
  "A sweet friendship refreshes the soul. An on-chain friendship refreshes the block.",
  "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you. The chain skips the small talk.",
  "Friendship is when people know all about you but like you anyway. Verified on-chain.",
  "A friend is a person with whom I may be sincere. Before him, I may think aloud. And post my unrealized losses.",
  "My friends are my estate. And I've just added one more address to the whitelist.",
  "Every friendship travels at some time through the black valley of despair. On Ritual, it also travels through the TEE enclave.",
  "A friend is one who believes in you when you have ceased to believe in yourself. And still holds.",
  "Keep away from those who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great. Find those people on Ritual.",
  "Each friend represents a world in us, a world possibly not born until they arrive, and it is only by this meeting that a new world is born. Or a new block.",
  "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom. And confirm our transactions.",
  "True friendship comes when the silence between two people is comfortable. Especially when waiting for block confirmation.",
  "A friend is one who overlooks your broken fence and admires the flowers in your garden. Even if your garden is a CSV file.",
  "A loyal friend laughs at your jokes when they're not so good and sympathizes with your problems when they're not so bad. Also sends you the alpha at 3am.",
  "Friendship isn't a big thing — it's a million little things. Like a million little transactions.",
  "Real friendship is when your friend comes online just when you needed someone. Or when the chain assigns them to you.",
  "It's not what we have in life, but who we have in our life that matters. The chain picked wisely.",
  "Friends are like walls — sometimes you lean on them and sometimes it's good just knowing they're there.",
  "A good friend is a connection to life and a road to the future.",
  "What draws people to be friends is that they see the same truth. They share it.",
  "Friendship is the comfort of knowing that even when you feel alone, you aren't. Especially not on Ritual.",
  "No friendship is an accident. This one was a transaction.",
  "A friendship that can cease was never real. An on-chain one is immutable.",
  "Friends are the family you choose. The chain chooses your Ritual family.",
  "I would rather have one true friend than a hundred acquaintances. The chain agrees — it only assigns one.",
  "The greatest healing therapy is friendship and love. And maybe a good airdrop.",
  "If you go looking for a friend, you're going to find they're very scarce. If you go out to be a friend, you'll find them everywhere. Or just use Ritual.",
  "Friendship is the hardest thing in the world to explain. It's not something you learn in school. But it is something you can learn from a smart contract.",
  "Good friends are like stars — you don't always see them but you always know they're there.",
  "Nothing but heaven itself is better than a friend who is really a friend. Or a confirmed transaction.",
  "Truly great friends are hard to find, difficult to leave, and impossible to forget.",
  "The capacity for friendship is God's way of apologizing for our families. The chain's way is this dApp.",
  "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes. Or let the chain assign them to you.",
  "A true friend is the greatest of all blessings.",
  "In everyone's life, at some time, our inner fire goes out. It is then burst into flame by an encounter with another human being. Or a block on Ritual Chain.",
  "It is one of the blessings of old friends that you can afford to be stupid with them. And post your worst trades.",
  "Friendship marks a life even more deeply than love. Love risks degenerating into obsession; friendship is never anything but sharing. Sometimes wallets.",
  "A friend is someone who gives you total freedom to be yourself — and cheers loudest when you're your weirdest.",
  "There are no strangers here, only friends you haven't met yet. The chain introduced you.",
  "Rare as is true love, true friendship is rarer. And now it's on-chain.",
  "The greatest sweetener of human life is friendship.",
  "Be slow to fall into friendship, but when thou art in, continue firm and constant. Like a validator node.",
  "We cannot tell the precise moment when friendship is formed. But we can tell the block number.",
  "Friendship is the only rose without thorns. Except for the gas fee.",
  "A friend is someone who makes it easy to believe in yourself. And who never sells the bottom.",
  "Friendship multiplies the good of life and divides its evils. Like sharding, but for the soul.",
  "Every new friend is a new adventure — the start of more memories. And another entry in pairings.json.",
  "Friendship is not about being inseparable, but about being separated and nothing changes.",
  "A single friend, chosen well, is worth a thousand acquaintances.",
  "Friendship is the only thing that can outlast a bear market.",
  "Some souls just understand each other upon meeting. The chain confirmed it.",
  "We didn't realize we were making memories. We just knew we were having fun — and signing transactions.",
  "Friends are the anchors that keep us from drifting into the void. Especially useful on a chain with TEEs.",
  "A friend is someone who sees through you and still enjoys the view.",
  "To the world you may be one person; but to one person you may be the world. The chain assigned you wisely.",
  "Friendship is born the second someone says: 'you too? I thought it was just me who didn't read the docs.'",
  "A good friend is like a four-leaf clover — rare, lucky, and worth keeping in your wallet.",
  "You don't need a reason to help people. But on Ritual, you do need a signature.",
  "The best mirror is an old friend. The best receipt is an old transaction.",
  "Friends: people who know you well and choose to like you anyway. Verified on-chain.",
  "Two people become best friends when they realize they share the same obsession and nobody else gets it.",
  "Friendship is the wine of life. The blockchain is the bottle.",
  "A true friend is someone who lets you have total freedom to be yourself — and loves you just the same.",
  "Wherever you are, it is your friends who make your world. And now, one more.",
];
