/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMembersRouteImport } from './routes/api/members'
import { Route as ApiMembersAvailableRouteImport } from './routes/api/members.available'
import { Route as ApiMembersAssignmentWalletRouteImport } from './routes/api/members.assignment.$wallet'
import { Route as ApiClaimRouteImport } from './routes/api/claim'
import { Route as ApiPairingsExportRouteImport } from './routes/api/pairings.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersRoute = ApiMembersRouteImport.update({
  id: '/api/members',
  path: '/api/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersAvailableRoute = ApiMembersAvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => ApiMembersRoute,
} as any)
const ApiMembersAssignmentWalletRoute = ApiMembersAssignmentWalletRouteImport.update({
  id: '/assignment/$wallet',
  path: '/assignment/$wallet',
  getParentRoute: () => ApiMembersRoute,
} as any)
const ApiClaimRoute = ApiClaimRouteImport.update({
  id: '/api/claim',
  path: '/api/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPairingsExportRoute = ApiPairingsExportRouteImport.update({
  id: '/api/pairings/export',
  path: '/api/pairings/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/pairings/export': typeof ApiPairingsExportRoute
  '/api/members/available': typeof ApiMembersAvailableRoute
  '/api/members/assignment/$wallet': typeof ApiMembersAssignmentWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/pairings/export': typeof ApiPairingsExportRoute
  '/api/members/available': typeof ApiMembersAvailableRoute
  '/api/members/assignment/$wallet': typeof ApiMembersAssignmentWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/claim': typeof ApiClaimRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/pairings/export': typeof ApiPairingsExportRoute
  '/api/members/available': typeof ApiMembersAvailableRoute
  '/api/members/assignment/$wallet': typeof ApiMembersAssignmentWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/claim'
    | '/api/members'
    | '/api/pairings/export'
    | '/api/members/available'
    | '/api/members/assignment/$wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/claim'
    | '/api/members'
    | '/api/pairings/export'
    | '/api/members/available'
    | '/api/members/assignment/$wallet'
  id:
    | '__root__'
    | '/'
    | '/api/claim'
    | '/api/members'
    | '/api/pairings/export'
    | '/api/members/available'
    | '/api/members/assignment/$wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiClaimRoute: typeof ApiClaimRoute
  ApiMembersRoute: typeof ApiMembersRouteWithChildren
  ApiPairingsExportRoute: typeof ApiPairingsExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim': {
      id: '/api/claim'
      path: '/api/claim'
      fullPath: '/api/claim'
      preLoaderRoute: typeof ApiClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members': {
      id: '/api/members'
      path: '/api/members'
      fullPath: '/api/members'
      preLoaderRoute: typeof ApiMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/available': {
      id: '/api/members/available'
      path: '/available'
      fullPath: '/api/members/available'
      preLoaderRoute: typeof ApiMembersAvailableRouteImport
      parentRoute: typeof ApiMembersRoute
    }
    '/api/members/assignment/$wallet': {
      id: '/api/members/assignment/$wallet'
      path: '/assignment/$wallet'
      fullPath: '/api/members/assignment/$wallet'
      preLoaderRoute: typeof ApiMembersAssignmentWalletRouteImport
      parentRoute: typeof ApiMembersRoute
    }
    '/api/pairings/export': {
      id: '/api/pairings/export'
      path: '/api/pairings/export'
      fullPath: '/api/pairings/export'
      preLoaderRoute: typeof ApiPairingsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiMembersRouteChildren {
  ApiMembersAvailableRoute: typeof ApiMembersAvailableRoute
  ApiMembersAssignmentWalletRoute: typeof ApiMembersAssignmentWalletRoute
}

const ApiMembersRouteChildren: ApiMembersRouteChildren = {
  ApiMembersAvailableRoute: ApiMembersAvailableRoute,
  ApiMembersAssignmentWalletRoute: ApiMembersAssignmentWalletRoute,
}

const ApiMembersRouteWithChildren = ApiMembersRoute._addFileChildren(
  ApiMembersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiClaimRoute: ApiClaimRoute,
  ApiMembersRoute: ApiMembersRouteWithChildren,
  ApiPairingsExportRoute: ApiPairingsExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
